version: "3.3"
services:
  localhost:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'waste'
      MYSQL_USER: 'root_user'
      MYSQL_PASSWORD: 'The_root_user1'
      MYSQL_ROOT_PASSWORD: 'The_root_user1'
    ports:
      - '3300:3306'
    volumes:
      - data:/var/lib/mysql
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - localhost
volumes:
  data: